name: Detect Secrets

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
